### ISSUE TITLE
Analisar recurso SMTR202307005758

### ISSUE THREAD

**Issue by eng-rodrigocunha** [prefeitura-rio/pipelines_rj_smtr#111]
## Etapas
- [ ] Reprocessar os arquivos da captura do GPS de Jun/23
  - [x] dev
  - [ ] prod
- [ ] Rematerializar Jun/23 na tabela de GPS
  - [x] dev
  - [ ] prod
- [ ] Reprocessar as viagens e a apuração do subsídio de Jun/23
   - [x] dev (entender divergencia entre prod e dev)
   - [ ] prod

Notebook: https://drive.google.com/file/d/1WhLv7D3GTG3qNpoDILWFwBBkJKFRo_PI/view?usp=drive_link

**Comment by eng-rodrigocunha** [comment]
Aguardando finalização por parte da CMO

**Comment by pixuimpou** [comment]
CMO finalizou a avaliação

**Comment by pixuimpou** [comment]
Não vamos subir para produção em razão da CMO ter pago apenas os serviços indicados no recurso
