### ISSUE TITLE
Adicionar descrições nas colunas das tabelas - Lote 2

### ISSUE THREAD

**Issue by pixuimpou** [prefeitura-rio/pipelines_rj_smtr#163]
https://docs.google.com/spreadsheets/d/1-uAvPgesjcNf8jKfMFsAUT6eO_Qn6L7xkULiGPcM_-k/edit?usp=sharing

br_rj_riodejaneiro_rdo
br_rj_riodejaneiro_stu
dashboard_gps_sppo
dashboard_subsidio_sppo
dashboards
gtfs

**Comment by akaBotelho** [comment]
Faltam as colunas codigo, id_migracao_trajeto e trajeto da view rj-smtr.br_rj_riodejaneiro_brt_gps.registros_historico. Aguardando resposta do Caio se ele tem conhecimento dessas informações.
