### ISSUE TITLE
Automatizar atualização do GTFS via pipeline

### ISSUE THREAD

**Issue by fernandascovino** [prefeitura-rio/pipelines_rj_smtr#21]
![Image](https://github.com/prefeitura-rio/pipelines_rj_smtr/assets/66736583/af084d6d-a18c-4269-b627-612bda69e187)

**TODO:** adicionar link do Miro

Link da planilha de controle: https://docs.google.com/spreadsheets/d/1Jn7fmaDOhuHMdMqHo5SGWHCRuerXNWJRmhRjnHxJ9O4/edit?pli=1#gid=0

**Comment by pixuimpou** [comment]
Está dando erro para baixar a planilha da OS com a api do Drive

**Comment by pixuimpou** [comment]
Adicionar docstrings
