### ISSUE TITLE
Recurso: Kms nos dias do RIR

### ISSUE THREAD

**Issue by pixuimpou** [prefeitura-rio/pipelines_rj_smtr#291]
Descrição: Não foram considerados os dias de RIR na apuração, nem os seus respectivos kms apurados.

Dias impactados: 13/09/24, 14/09/24, 15/09/24

**Comment by pixuimpou** [comment]
subir para produção

**Comment by eng-rodrigocunha** [comment]
Subiu para produção em 2024-11-29T10:23:38.034777
