### ISSUE TITLE
[FEATURE] Migrar pipelines :rocket: :partying_face: :balloon: 

### ISSUE THREAD

**Issue by Hellcassius** [prefeitura-rio/pipelines_rj_smtr#31]
- [x] Adicionar prefixo `migracao` aos datasets atualizados pelas pipelines a serem migrads
- [x] Criar um reporte diário comparativo entre prefect 1 e 2  
     - [x] Total runs (prefect 1 vs prefect 2), quantidade de falhas (prefect 1 vs prefect 2)
- [x] Listar todos os datasets atualizados de maneira programática
- [x] Validar os dados no BQ comparando com os dados de Produção
    - [x] Definir testes
    - [x] Definir responsáveis por cada dataset
    - [x] Definir prazos para a migração efetiva de cada dataset

**Comment by Hellcassius** [comment]
29/05/24 - Ligar schedule do SPPO neste repo, desligar no repo antigo:
PR ligando: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/38
PR desligando no repo antigo: https://github.com/prefeitura-rio/pipelines/pull/695

**Comment by pixuimpou** [comment]
13/06/24 - Ligar schedule do controle financeiro neste repo, desligar no antigo:
PR ligando: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/60
PR desligando no repo antigo: https://github.com/prefeitura-rio/pipelines/pull/702

**Comment by pixuimpou** [comment]
18/06/24 - Migra pipelines br_rj_riodejaneiro_stu
PR: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/64

**Comment by akaBotelho** [comment]
19/06/24 - Migra pipelines br_rj_riodejaneiro_stpl_gps 
PR: [#66](https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/66)

**Comment by pixuimpou** [comment]
19/06/24 - Ligar schedule do veiculo neste repo, desligar no antigo:
PR ligando: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/65
PR desligando no repo antigo: https://github.com/prefeitura-rio/pipelines/pull/705

**Comment by akaBotelho** [comment]
20/06/2024 - Migra pipelines br_rj_riodejaneiro_onibus_gps_zirix
PR ligando: [#67](https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/67)
PR desligando no repo antigo: [prefeitura-rio/pipelines#704](https://github.com/prefeitura-rio/pipelines/pull/704)

**Comment by akaBotelho** [comment]
20/06/2024 - Migra pipelines br_rj_riodejaneiro_viagem_zirix
PR ligando: [#68](https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/68)
PR desligando no repo antigo: [prefeitura-rio/pipelines#706](https://github.com/prefeitura-rio/pipelines/pull/706)

**Comment by vtr363** [comment]
20/06/2024 - liga schedule br_rj_riodejaneiro_gtfs
PR ligado: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/62

**Comment by pixuimpou** [comment]
24/06/2024 - Migra pipelines br_rj_riodejaneiro_rdo e br_rj_riodejaneiro_diretorios
PR ligando: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/76
PR desligando no repo antigo: https://github.com/prefeitura-rio/pipelines/pull/709/

**Comment by akaBotelho** [comment]
25/06/2024 - Migra pipelines projeto_subsidio_sppo
PR ligando: [#75](https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/75)
PR desligando no repo antigo: [prefeitura-rio/pipelines#708](https://github.com/prefeitura-rio/pipelines/pull/708)

**Comment by pixuimpou** [comment]
25/06/2024 - Migra pipelines br_rj_riodejaneiro_brt_gps
PR ligando: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/80
PR desligando no repo antigo: https://github.com/prefeitura-rio/pipelines/pull/710

**Comment by pixuimpou** [comment]
03/07/2024 - Migra pipeline de captura do gps do validador da Jaé
PR ligando: https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/89
PR desligando no repo antigo: https://github.com/prefeitura-rio/pipelines/pull/711
